sudo: true
language: java
cache:
  directories:
  - ".docker"
  - ".autoconf"
  - "$HOME/.m2"
services:
- docker
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
  - "/^feature\\/.*$/"
  - "/^hotfix\\/.*$/"
before_install:
- docker-compose -f ala-nameservice.yml up -d
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn clean deploy'
after_script:
- docker-compose -f ala-nameservice.yml kill
env:
  global:
  - secure: HKSvRnZ3wMBVXN4s4lr3RqYO49XfMuIsONAEtQ+Bh3X9YxWS+xARi+cW17JhFRIoHWNO3JnbCZQBS38KCQ+c68r8I4egHihLftQoO6KxnHw9l5B96WKZDTjktiis2dCmjMcL8/flHJKcvea+ckvzV4CFU888M+jZPjThqftx8Wdujbaabd95bjmgUZWdzV05E9nWWhHVC3qR7x/woSbEjjpWtP+vJyCJR8YIhfTQPXhqcbnVmrts4vv15+N1GvvLrr0I76YyMVDH8YUJqqoAcQVanaYbl0RNI0f+jZbEMv5D+WfZYJ2nnoUd22845YUIHq/ulpQT2DF/Ydssgi7LMXiYbFxl7ClzFI4rwv+1uWeNLMhjPczCP3Oc6YnRD++YTYX3rRlemp1ekRE6tfYhngygHQKB/IoeXKIJ6Y3Y7N0r7pNf8oGRlA4tdsxWZIBwvQW437LddzYKyrU/Cf9yLYfVWpcKzKA7leEa8vN6235T9Qp69yZBGzVEEv3YixJ6wQgYx2k7VOjZb911DIeiP4ul09pPSWW55wKRKkyxGkjLHiwd+G+9OtpHuhQPWJhC55omMgJ8XjZrDar9WG4fwOWf/Gk95WODr3VIN/EH5tX5NZ5DDbClLvMsjb9uecB3jJaAGLZcJiA6bXyOrLj/mnfluWiIGBjENOvQDqdEkTc=
  - secure: eFxmjEZdVww6xuZdaOJKOaIKzoa+w2CsgUxrz4Jmv1WYvMc+AUyZnuGkuXQAfUajRClK33tOTfZ8Rt32jznfZxuG0ce7QU4nkMtXkNBBCx3V5hHuS4CXvt07kcsr6EymuxoV87xkzUBQ6bo5xECdfecfptguAeR8ZXiqe2uKZu6MGORl9OEcnfuox8XCwjszc9HlNwmaMpn+7ClU6rESZD6i/UbOClV2P4MZ/VJ/UID+fy6rQ5jJG+tUto5fU9lAKlmM23PqoqaIXolyoD4NST1tkYWLHZcoic1+owdqoR4xL6aApol0NwYEb0NXvgeTMCjQfIMzbawGKkyE5LJskdzrRRPPJtRGYdzNnNT6Mqh2kCN7PEunTC2GSu1YBEyEojPU/dPVySmi2QSX8kBeMTPa3mKn0x4pe+Z4vGDbuShe4IojWZq8zcGCBaia3TBUtR0o1W4ogXDR7djfHhWfgmT/5ku7/O1SWOTdaSiwUCDsxvCUCD/qiEU7K7dibiwCS321yocspzniA+I5/oYQcQlJogyr7lDxmklqS39PxBYIZHR+yC1Kn/g0Vr3uEgpjuOF4uIsXHEPs5QWeZX9VbTjyY5ixOKr4xHv8LC8x1HPd+pdBhxHzMq1OLKGazbmGi261TtfayOeB4/ik9B1hhfMhSfm+4UV3/PJf7/0pOuc=
