sudo: true
language: java
cache:
  directories:
  - ".docker"
  - ".autoconf"
  - "$HOME/.m2"
services:
- docker
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
  - "/^feature\\/.*$/"
  - "/^hotfix\\/.*$/"
before_install:
- docker-compose -f ala-nameservice.yml up -d
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn -P travis clean deploy'
after_script:
- docker-compose -f ala-nameservice.yml kill
env:
  global:
  - secure: uxjw2DhMt8i8vx49Xoj6u1UJk0Y3fDn7PBI+0BCJlPovkFkLxxOPy+kJRkhWEhECwULuDG0jYZULjNCg84C9M3FBdO2dgw6mqMhdLTnT71BZr00U5UrsxYC81PkID70dHymcg2Rkuqymg3NALO0BKieFPx5sGAGiladegAuOOlgr+Csfe3e1QO8kgZCrlLUh3RVzmDWRdFB3ZyoFcAdkpWebyl6y/pa/ELJEADy8ASNrNBPH4fcuw147gevOC8CGk0RSzzo7VZxeTXLgwDpV+q5QanVvgmbVF//JFGXuvU+Wp50tMLSPI28dGA62uS+0WU5MTLTNeFhbDj/iOJ+ottcxv4vZTMiTw3lozfm8Krzm/ioM3o8vPJRPfzsndAYhMJDS+osZmlbkLfCaWWTiHq7JcHWQt4Eydo4Jp0JDm5BBK6yVnu5fDqdLJpgClnHTfAK8xrhWqWKsTEOoXD9J1yPj6JOai3nF6P4EyD1wltA59xi6YbCfx4e4WgRMMYXwIwe88M+qpkeNSNiMQ8sxY5ByU9WTLihBcGlVBE7V3h2xM3qQlqzqhnP7MJR0640MaNhuRjugt2BjTwr25FrEWh1R5PVORDGhXomH1JbNzEADojo2b9nCD16ZfBknabdfZc2MTkPG1YJP8kPd5EpKKLgSCRJLh+ae2VnYOCf3v7M=
  - secure: U1b9C+spFGpb7Knbn3hM8CS41qRunk3pnetPJZBoM167u7gCoINRpImqQi7zu2vxWZZ66bj3W06+qzqbUWyD263cqth5wqAg4qW7UowmtsGs1ueF+OAdyW1TSCFHOFyLyXcYTpX68G8IJCnjPZeIwHGEeOa9GHnE00CZEc3M+0iJ4J4PE85kgpx3+uURhg+v3SnmRxezj8/iUYu+bpDNP5lCuG/fWRpIPUJCiGZGvL9wd8hn10jwrs/ZwvrkruPBrT9YLlhWtaLHcwc0Exl3iuBvIqzXbrpYHyhWSVQy/LaF8v71Bjt7n4WmlvxE3iELc9fgyLh+De7s6mfOYBkX4afNTESzTJnj5HkmmmiUqwlpfckMMX5zhCHEYi2pU7vF3R+rtF2kWlKMB9LvM/DdciOsF/kPRjVwhHGK7ufJoMYFjog1jvZu/PdG4rT08DA3SnHgljdeWVKpAAtmxGRlXqgNOFdyPz/h3eQN2ip9ILUJ9MX7rPIe3GFaB2Ik14Geintq4uKDYr+zoL1rZyiojB4SbKcXqxweDMPaZvm9raAaP6mbqWo4XwugAJTX4WVxoUIPEDyUOMdlVX6rAraaVN3+eAnMQnfR+fGebC9DKkxZSF8mAqHcm0JXmf2n/SGaUQ7wIS3nICNrEntvA04ToGLMT071bz5tl5n5rzT3Qxk=
