sudo: true
language: java
cache:
  directories:
  - ".docker"
  - ".autoconf"
  - "$HOME/.m2"
services:
- docker
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
  - feature/uuid-management
  - "/^hotfix\\/.*$/"
before_install:
- docker-compose -f ala-nameservice.yml up -d --remove-orphans
- docker-compose -f solr8.yml up -d --remove-orphans
- mkdir -p $HOME/.m2; wget -q -O $HOME/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
- sudo mkdir -p /data/pipelines-shp; sudo wget -O /data/pipelines-shp/pipelines-shapefiles.zip https://pipelines-shp.s3-ap-southeast-2.amazonaws.com/pipelines-shapefiles.zip
- cd /data/pipelines-shp
- sudo unzip pipelines-shapefiles.zip
- ls -laF
- cd $TRAVIS_BUILD_DIR
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn clean deploy'
after_script:
- docker-compose -f ala-nameservice.yml kill
- docker-compose -f solr8.yml kill
after_success:
  - mvn clean test jacoco:report coveralls:report
env:
  global:
  - secure: aGcb0l1YsVSF41blsirQ5orm1ifO/FdOPt7O01tLHTBqPSnQN3CMih2j/JA9i1LkXbQ8BelzffTsH964Q0F9YfDy1ZPkjh6KW5Bm4aLCl5oRie33pvLcLn6QdFWWLRNcQcWRPX94T1ejQAvLWyFfaEb6XtdVNsCH7BdZmISkMqkfDy9nr3WxUE31Dti65i8r3q/J81//24hvjngtxqm964wUvsyVoxcKcSrGFI21P6aWD7uOsgDWOFvWWzf9jNzxPZdK0ZVnjy7f2rzFr8yBmZHqUzPdIik75gJkIVpfwfqwagaDmxe955suRXnTxKyzOx2c/zb+JZd8LtEtkU86NSTXmHFYJzagKaarhUm+Vo8RBA/Q5HNYVELapD3AQu+5xYsgndTXkGAk1oFiCcl524YtLtVGxuUy0DKeew2eQrJRI+G8mCqG18Iw5n/wn2w3Mjd6c+WRKRUF6HiVtrNJmVdHdUz13KSuHYgQmiTIGlT3cgCanKkeduHF6c3d01zokeLqtmZlZ74Usa4gxrMhMttq/OpvjasAxS48sXG8mmSELlCGeAy0ygUFgHqM3PvdYmmaA9XzHMxa1EHsSlVKTzFzl02pdv1goFTR5xa8DiGt2NgK4i0L7tfW2qlFjDMEgnThNqM8yda33YqbBCRoFBf5gbRypQ0AWwqqn1BV5N4=
  - secure: UtLtoh2x+tLZhMShAbZ0/IQYmkQNjXJ6G5OOzYl5AYuXkoZev5OTMc76aPtoQ7WjupKYOLHDUeZK0GIZgxzAxh01JObu0GI7ymX9j8GYea/dw90U5Uj8K9QBnqkVgNdxwkYyMnhvDHcZHVhSbkbtVvRSdvrEBqkxg/NJSRjWGZG/FFPz84IC/XAWLwJqJtdDrlAX8QVTmPyg9iXKh0Pceg9ozpQxSjpqy2WUplNEhkuzcGsuq8o7qtAzHGxSTiB/huXFfClfCd1PSveDJ1KIErtQeku2+i1aqqUFHY9tMiXfp3aptvnFMfDaR0IaKSBSEWzg5LfXr2ueYcv9ARDOpElizEqT8GrTd5dlxBBAWpqQK9nASBXiq3Qvxr3cIx1/VaiqlCgj70Lq2n8ygQOF2RSIp0VsJOxiStIA5JXfTJYqton3YiIzIIoYN9WQPA1wWYtIXCJQmlISfbRx3C+DyeRR0lUHqkkIpBCvCZ3fI4Lv212N8yhY5LG/RzyKeFW1GjFjPqp+RBTW+Wel0tNgOoHdHBpkUaUxoPWsDhgzOVk7rZvokRRd+w7eXxJINaaX+w2yU676Bs+EXkmx1DKXZUwTwbVrNYQ9oR6i4sGOORoINh4QhqlCfKbjQ/X6XGxO3ukprT17e40rmUO2yzp1zBohJPUOzALSs44N58AwoRw=
