version: "3.2"

services:
  solr:
    image: biocache-pipelines-solr7:v1
    container_name: biocache-pipelines-solr7
    ports:
      - 9983:9983
      - 8983:8983
    environment:
      SOLR_PORT: 8983
      SOLR_HOST: localhost
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f
