/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.gbif.pipelines.io.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

import org.apache.beam.sdk.coders.AvroCoder;
import org.apache.beam.sdk.coders.DefaultCoder;
@DefaultCoder(AvroCoder.class)
@SuppressWarnings("all")
/** Issue information */
@org.apache.avro.specific.AvroGenerated
public class IssueRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -75627971908866863L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IssueRecord\",\"namespace\":\"org.gbif.pipelines.io.avro\",\"doc\":\"Issue information\",\"fields\":[{\"name\":\"issueList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<IssueRecord> ENCODER =
      new BinaryMessageEncoder<IssueRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IssueRecord> DECODER =
      new BinaryMessageDecoder<IssueRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<IssueRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<IssueRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<IssueRecord>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this IssueRecord to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a IssueRecord from a ByteBuffer. */
  public static IssueRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<java.lang.String> issueList;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IssueRecord() {}

  /**
   * All-args constructor.
   * @param issueList The new value for issueList
   */
  public IssueRecord(java.util.List<java.lang.String> issueList) {
    this.issueList = issueList;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return issueList;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: issueList = (java.util.List<java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'issueList' field.
   * @return The value of the 'issueList' field.
   */
  public java.util.List<java.lang.String> getIssueList() {
    return issueList;
  }

  /**
   * Sets the value of the 'issueList' field.
   * @param value the value to set.
   */
  public void setIssueList(java.util.List<java.lang.String> value) {
    this.issueList = value;
  }

  /**
   * Creates a new IssueRecord RecordBuilder.
   * @return A new IssueRecord RecordBuilder
   */
  public static org.gbif.pipelines.io.avro.IssueRecord.Builder newBuilder() {
    return new org.gbif.pipelines.io.avro.IssueRecord.Builder();
  }

  /**
   * Creates a new IssueRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IssueRecord RecordBuilder
   */
  public static org.gbif.pipelines.io.avro.IssueRecord.Builder newBuilder(org.gbif.pipelines.io.avro.IssueRecord.Builder other) {
    return new org.gbif.pipelines.io.avro.IssueRecord.Builder(other);
  }

  /**
   * Creates a new IssueRecord RecordBuilder by copying an existing IssueRecord instance.
   * @param other The existing instance to copy.
   * @return A new IssueRecord RecordBuilder
   */
  public static org.gbif.pipelines.io.avro.IssueRecord.Builder newBuilder(org.gbif.pipelines.io.avro.IssueRecord other) {
    return new org.gbif.pipelines.io.avro.IssueRecord.Builder(other);
  }

  /**
   * RecordBuilder for IssueRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IssueRecord>
    implements org.apache.avro.data.RecordBuilder<IssueRecord> {

    private java.util.List<java.lang.String> issueList;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.gbif.pipelines.io.avro.IssueRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.issueList)) {
        this.issueList = data().deepCopy(fields()[0].schema(), other.issueList);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing IssueRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(org.gbif.pipelines.io.avro.IssueRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.issueList)) {
        this.issueList = data().deepCopy(fields()[0].schema(), other.issueList);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'issueList' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getIssueList() {
      return issueList;
    }

    /**
      * Sets the value of the 'issueList' field.
      * @param value The value of 'issueList'.
      * @return This builder.
      */
    public org.gbif.pipelines.io.avro.IssueRecord.Builder setIssueList(java.util.List<java.lang.String> value) {
      validate(fields()[0], value);
      this.issueList = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'issueList' field has been set.
      * @return True if the 'issueList' field has been set, false otherwise.
      */
    public boolean hasIssueList() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'issueList' field.
      * @return This builder.
      */
    public org.gbif.pipelines.io.avro.IssueRecord.Builder clearIssueList() {
      issueList = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IssueRecord build() {
      try {
        IssueRecord record = new IssueRecord();
        record.issueList = fieldSetFlags()[0] ? this.issueList : (java.util.List<java.lang.String>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IssueRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<IssueRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IssueRecord>
    READER$ = (org.apache.avro.io.DatumReader<IssueRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
