general:
  targetPath: hdfs://aws-spark-quoll-1.ala:9000/pipelines-data
  attempt: 1
  hdfsSiteConfig: /efs-mount-point/hdfs-site.xml
  coreSiteConfig: /efs-mount-point/hdfs-site.xml

interpret:
  appName: Interpretation for {datasetId}
  inputPath: hdfs://aws-spark-quoll-1.ala:9000/pipelines-data/{datasetId}/1/verbatim.avro

sample-avro:
  appName: Add Sampling for {datasetId}
  useExtendedRecordId: true

index:
  appName: SOLR indexing for {datasetId}
  runner: SparkRunner
