# Here we can override some config from la-pipelines.yml instead of modifying it.
# This configuration file is specifically for overrides for jobs ran with embedded spark.
#
# This file is referenced in the *-spark-embedded.sh bash scripts.